{% set name = "memray" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fcf306eae2c00144920b01913f42fa7f235af7a80fa3226ab124672a5cb1d8f

build:
  number: 0
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64]
    - export LDFLAGS="${LDFLAGS} -pthread"  # [aarch64]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pkgconfig
    - cython >=0.29.31
    - libunwind {{ libunwind }}  # [linux]
    - lz4-c {{ lz4_c }}
  run:
    - python
    - jinja2 >=2.9
    - typing_extensions  # [py<38]
    - rich >=11.2.0
    - textual >=0.41.0
    # Version through run_exports
    - libunwind

test:
  imports:
    - memray
  requires:
    - pip
  commands:
    - pip check
    - memray -h

about:
  home: https://github.com/bloomberg/memray
  summary: Memray is a memory profiler for Python
  description: |
    Memray is a memory profiler for Python. It can track memory allocations in
    Python code, in native extension modules, and in the Python interpreter
    itself. It can generate several different types of reports to help you
    analyze the captured memory usage data. While commonly used as a CLI tool,
    it can also be used as a library to perform more fine-grained profiling
    tasks.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - src/vendor/libbacktrace/LICENSE
  doc_url: https://bloomberg.github.io/memray
  dev_url: https://github.com/bloomberg/memray

extra:
  recipe-maintainers:
    - matthiasdiener
